[package]
name = "sunbeam-meet-migrations"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://src.sunbeam.pt/studio/sunbeam-meet"
authors = ["Sunbeam Studios"]
rust-version = "1.82"
publish = false
description = "SQLx migrations for sunbeam-meet."

[dependencies]
sqlx.workspace = true
